version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "8080:8080"
    volumes:
      # Mount source code for hot reloading
      - .:/app
      # Exclude node_modules to use container's version
      - /app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
    # Restart policy
    restart: unless-stopped
